# Generated by Django 2.1.4 on 2019-01-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coderelease', '0021_auto_20181224_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name', models.CharField(max_length=200, verbose_name='Platfrom name')),
                ('plat_url', models.TextField(verbose_name='url')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderelease.ReleaseEnv', verbose_name='环境名')),
            ],
            options={
                'verbose_name': '环境主机',
                'verbose_name_plural': '环境主机',
            },
        ),
    ]
