# Generated by Django 2.1.4 on 2019-01-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformmanagement',
            options={'verbose_name': 'Platform management', 'verbose_name_plural': 'Platform management'},
        ),
    ]
