# Generated by Django 2.1.3 on 2018-12-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0002_auto_20181207_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasehost',
            name='port',
            field=models.IntegerField(verbose_name='SSH端口'),
        ),
    ]
