# Generated by Django 2.1.3 on 2018-12-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0003_auto_20181207_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseconfig',
            name='env',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coderelease.ReleaseEnv'),
        ),
    ]
