# Generated by Django 2.1.3 on 2018-12-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0004_auto_20181207_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('principal', models.CharField(max_length=50, verbose_name='负责人')),
                ('git_url', models.TextField(verbose_name='git地址')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('env_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderelease.ReleaseEnv', verbose_name='环境')),
                ('pro_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderelease.ReleaseProjectType', verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
    ]
