# Generated by Django 2.1.3 on 2018-12-12 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0005_addprojectrecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasehost',
            name='domain',
            field=models.CharField(default=datetime.datetime(2018, 12, 12, 18, 59, 7, 615364), max_length=100, verbose_name='域名'),
            preserve_default=False,
        ),
    ]
