# Generated by Django 2.1.3 on 2018-12-13 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0006_releasehost_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasehost',
            name='domain',
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='domain',
            field=models.CharField(default=datetime.datetime(2018, 12, 13, 9, 49, 19, 889261), max_length=100, verbose_name='域名'),
            preserve_default=False,
        ),
    ]
