# Generated by Django 2.1.3 on 2018-12-13 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0007_auto_20181213_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectrecode',
            name='branch',
            field=models.CharField(default=datetime.datetime(2018, 12, 13, 10, 1, 26, 797961), max_length=32, verbose_name='分支'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='host_list',
            field=models.CharField(default=datetime.datetime(2018, 12, 13, 10, 1, 34, 573179), max_length=100, verbose_name='主机信息'),
            preserve_default=False,
        ),
    ]
