# Generated by Django 2.1.3 on 2018-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0008_auto_20181213_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='host_list',
            field=models.CharField(default='[]', max_length=100, verbose_name='主机信息'),
        ),
    ]
