# Generated by Django 2.1.3 on 2018-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0009_auto_20181213_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='域名'),
        ),
    ]
