# Generated by Django 2.1.3 on 2018-12-17 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0011_releaseprojecttype_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectrecode',
            name='data_path',
            field=models.TextField(default=datetime.datetime(2018, 12, 17, 20, 3, 20, 953415), verbose_name='部署路径'),
            preserve_default=False,
        ),
    ]
