# Generated by Django 2.1.3 on 2018-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0014_addprojectrecode_release_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectrecode',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
