# Generated by Django 2.1.3 on 2018-12-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0015_addprojectrecode_u_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='pro_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='项目名称'),
        ),
    ]
