# Generated by Django 2.1.3 on 2018-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0016_auto_20181218_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectrecode',
            name='api_server',
            field=models.CharField(default='', max_length=200, verbose_name='API Server'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='docker_registry',
            field=models.CharField(default='', max_length=200, verbose_name='镜像库'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='jenkins_credentials_id',
            field=models.CharField(default='', max_length=200, verbose_name='凭据'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='jenkins_password',
            field=models.CharField(default='', max_length=100, verbose_name='jenkins 密码'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='jenkins_url',
            field=models.TextField(default='', verbose_name='jenkins 地址'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='jenkins_username',
            field=models.CharField(default='', max_length=100, verbose_name='jenkins 用户'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='namespace',
            field=models.CharField(default='', max_length=100, verbose_name='命名空间'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='rabbit_pass',
            field=models.CharField(default='', max_length=100, verbose_name='rabbit 密码'),
        ),
        migrations.AddField(
            model_name='addprojectrecode',
            name='redis_pass',
            field=models.CharField(default='', max_length=100, verbose_name='redis 密码'),
        ),
    ]
