# Generated by Django 2.1.4 on 2018-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0017_auto_20181218_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='host_list',
            field=models.TextField(default='[]', max_length=100, verbose_name='主机信息'),
        ),
    ]
