# Generated by Django 2.1.4 on 2018-12-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0018_auto_20181224_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasehost',
            name='kwargs',
            field=models.TextField(default="{'release_dir_name':'dest','mysql_user':'default','mysql_pass':'default'}", verbose_name='kwargs'),
        ),
    ]
