# Generated by Django 2.1.4 on 2018-12-24 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0019_releasehost_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectrecode',
            name='kwargs',
            field=models.TextField(default=datetime.datetime(2018, 12, 24, 17, 58, 3, 845139), verbose_name='kwargs'),
            preserve_default=False,
        ),
    ]
