# Generated by Django 2.1.4 on 2018-12-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0020_addprojectrecode_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='host_list',
            field=models.TextField(default='[]', verbose_name='主机信息'),
        ),
        migrations.AlterField(
            model_name='releasehost',
            name='kwargs',
            field=models.TextField(default='{}', verbose_name='kwargs'),
        ),
    ]
