# Generated by Django 2.1.4 on 2019-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0021_auto_20181224_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectrecode',
            name='pro_name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
