# Generated by Django 2.1.3 on 2018-12-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_up', models.TextField(verbose_name='UP')),
                ('pod_down', models.TextField(verbose_name='DOWN')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': 'POD状态监控',
                'verbose_name_plural': 'POD状态监控',
            },
        ),
    ]
