# Generated by Django 2.1.3 on 2018-12-05 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderelease', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podstatus',
            name='env',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coderelease.ReleaseEnv'),
            preserve_default=False,
        ),
    ]
