# Generated by Django 2.1.4 on 2018-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='UserName')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('e_time', models.DateTimeField(auto_now=True, verbose_name='end time')),
                ('overtime_hours', models.IntegerField(max_length=20, verbose_name='working hours')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
    ]
