# Generated by Django 2.1.4 on 2018-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='overtime_hours',
            field=models.IntegerField(verbose_name='working hours'),
        ),
    ]
