# Generated by Django 2.1.4 on 2019-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perecord', '0002_auto_20181227_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='overtime_hours',
            field=models.CharField(max_length=20, verbose_name='working hours'),
        ),
    ]
