# Generated by Django 2.1.4 on 2019-01-02 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perecord', '0003_auto_20190102_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='c_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 2, 16, 23, 11, 35887), verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtime',
            name='e_time',
            field=models.CharField(max_length=100, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='s_time',
            field=models.CharField(max_length=100, verbose_name='start time'),
        ),
    ]
